/* eslint-disable */
module.exports = {
  SET_USER: 'SET_USER',
  SET_TOKEN: 'SET_TOKEN',
  SET_LIST_PRODUCT: 'SET_LIST',
  SET_LIST_CATEGORY: 'SET_LIST_CATEGORY',
  SET_LIST_SELLER: 'SET_LIST_SELLER'
}
